In [2]:
## operations
## bool sum multiply

In [3]:
import numpy as np

In [6]:
arr = np.random.randint(1,100,30)

In [7]:
arr

array([80, 52, 71, 91, 98, 74, 21, 93,  2, 24, 34, 20, 93, 68, 57, 73, 21,
       61, 62, 98, 88, 41, 57, 21, 74, 78, 28, 38, 38, 55])

In [8]:
# lookfor particular elements
arr > 50 

array([ True,  True,  True,  True,  True,  True, False,  True, False,
       False, False, False,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True, False,  True,  True, False,
       False, False,  True])

In [22]:
 newArr = arr < 50

In [23]:
arr[newArr] # return elements that smaller then 50 # what an amazing thing for c coders 

array([21,  2, 24, 34, 20, 21, 41, 21, 28, 38, 38])

In [24]:
newArr = arr[newArr]

In [25]:
newArr

array([21,  2, 24, 34, 20, 21, 41, 21, 28, 38, 38])

In [26]:
newArr[:] = 10000

In [27]:
arr

array([80, 52, 71, 91, 98, 74, 21, 93,  2, 24, 34, 20, 93, 68, 57, 73, 21,
       61, 62, 98, 88, 41, 57, 21, 74, 78, 28, 38, 38, 55])

In [28]:
newArr

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000])

In [29]:
arr + arr

array([160, 104, 142, 182, 196, 148,  42, 186,   4,  48,  68,  40, 186,
       136, 114, 146,  42, 122, 124, 196, 176,  82, 114,  42, 148, 156,
        56,  76,  76, 110])

In [30]:
newArr + newArr

array([20000, 20000, 20000, 20000, 20000, 20000, 20000, 20000, 20000,
       20000, 20000])

In [31]:
newArr

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000])

In [32]:
arr

array([80, 52, 71, 91, 98, 74, 21, 93,  2, 24, 34, 20, 93, 68, 57, 73, 21,
       61, 62, 98, 88, 41, 57, 21, 74, 78, 28, 38, 38, 55])

In [33]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
arr / 1000

array([0.08 , 0.052, 0.071, 0.091, 0.098, 0.074, 0.021, 0.093, 0.002,
       0.024, 0.034, 0.02 , 0.093, 0.068, 0.057, 0.073, 0.021, 0.061,
       0.062, 0.098, 0.088, 0.041, 0.057, 0.021, 0.074, 0.078, 0.028,
       0.038, 0.038, 0.055])

In [36]:
np.max(arr)

98

In [37]:
np.min(arr)

2

In [ ]:
# may find new things numpy.org