In [8]:
# disturbution gauss normal
# random
import numpy as np

temp = np.random.randn(5)
print(temp)


[ 0.71787656 -0.72300347 -0.16853688  2.19765119 -1.05222081]


In [13]:
temp = np.random.randn(3,3)
temp


array([[-0.06515356,  1.28138571, -1.62512901],
       [ 0.32592239,  0.12440485,  0.16489207],
       [-0.42585815, -0.77719437, -0.21176274]])

In [21]:
temp = np.random.randint(2,10) # interval 2 <= x < 10
temp

9

In [23]:
temp = np.random.randint(-10,100,20)
temp

array([35, 72,  1, 87, 26, 85, 70, 92, 13,  3,  1, 57,  6, 48, 37, 39, 68,
       57,  9, -5])

In [24]:
type(temp)

numpy.ndarray

In [25]:
temp = np.arange(30)
temp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])