In [1]:
import numpy as np

In [2]:
myArr = np.arange(0,15)

In [3]:
myArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
#slicing


In [5]:
myArr[3:5]

array([3, 4])

In [6]:
myArr[4:10]

array([4, 5, 6, 7, 8, 9])

In [7]:
myArr[0:5] = -5

In [8]:
myArr

array([-5, -5, -5, -5, -5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
Arr2 = np.arange(0,24)

In [18]:
Arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
tempArr = Arr2[4:9]

In [20]:
tempArr

array([4, 5, 6, 7, 8])

In [21]:
Arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
tempArr[:] =+100 #do not tempArr = +- 

In [24]:
tempArr

array([100, 100, 100, 100, 100])

In [25]:
Arr2 #vov original array is changed... caution !! there must be a pointer :) from C

array([  0,   1,   2,   3, 100, 100, 100, 100, 100,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [26]:
Arr2 = np.arange(0,25)
Arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
temp = Arr2.copy()

In [28]:
temp[:] = 1000
temp

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
       1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
       1000, 1000, 1000])

In [29]:
Arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
#dimensions multidimesion arrays

In [31]:
#matrix

In [39]:
matrix = [(1,2,3),(4,5,6),(7,8,9)] # normal list data type

In [40]:
matrix

[(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [41]:
matrix = np.array(matrix) # to matrix

In [42]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
matrix[0,1]  # [line, colomn]

2

In [48]:
matrix[2,2] # or may use like this [line][colomn]

9

In [50]:
matrix[2][2]

9

In [51]:
# slicing multidiminsions array

In [52]:
tempMatrix = matrix.copy()

In [53]:
tempMatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
tempMatrix = matrix[:,2:]
tempMatrix

array([[3],
       [6],
       [9]])

In [59]:
tempMatrix = matrix[1:,:]

In [60]:
tempMatrix

array([[4, 5, 6],
       [7, 8, 9]])

In [61]:
tempMatrix = matrix[:2,:]

In [62]:
tempMatrix

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
tempMatrix = matrix[:,0:2]

In [64]:
tempMatrix

array([[1, 2],
       [4, 5],
       [7, 8]])

In [67]:
newList = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]]

In [69]:
newList

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]

In [70]:
tempMatrix = np.array(newList)

In [71]:
tempMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [76]:
tempMatrix[[3,2,1]] #fancy indexing :) 

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9]])

In [77]:
tempMatrix[[2,3]]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])