In [4]:
import numpy as np
temp = np.arange(30)
temp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
temp = np.random.randint(-50,50,60) #25 elemens interao 0-50

In [24]:
temp

array([ 12,  35,  38,   8,  14,   2,  37,  47, -15,  23,  -9,  11, -43,
         0, -45,  10, -20, -15,  13, -37, -25, -40, -17,  25, -30, -21,
        27,   0,  12,  -6,  34,  31, -21,   1, -12,  26,  33, -37, -37,
        26,  43, -13, -23, -40, -31,  46, -16, -44,  36, -12,  38, -29,
       -47,   5, -40, -39, -24,   7, -22,  19])

In [25]:
temp.reshape(12,5)

array([[ 12,  35,  38,   8,  14],
       [  2,  37,  47, -15,  23],
       [ -9,  11, -43,   0, -45],
       [ 10, -20, -15,  13, -37],
       [-25, -40, -17,  25, -30],
       [-21,  27,   0,  12,  -6],
       [ 34,  31, -21,   1, -12],
       [ 26,  33, -37, -37,  26],
       [ 43, -13, -23, -40, -31],
       [ 46, -16, -44,  36, -12],
       [ 38, -29, -47,   5, -40],
       [-39, -24,   7, -22,  19]])

In [26]:
temp.reshape(4,15)

array([[ 12,  35,  38,   8,  14,   2,  37,  47, -15,  23,  -9,  11, -43,
          0, -45],
       [ 10, -20, -15,  13, -37, -25, -40, -17,  25, -30, -21,  27,   0,
         12,  -6],
       [ 34,  31, -21,   1, -12,  26,  33, -37, -37,  26,  43, -13, -23,
        -40, -31],
       [ 46, -16, -44,  36, -12,  38, -29, -47,   5, -40, -39, -24,   7,
        -22,  19]])

In [27]:
temp.reshape(6,10)

array([[ 12,  35,  38,   8,  14,   2,  37,  47, -15,  23],
       [ -9,  11, -43,   0, -45,  10, -20, -15,  13, -37],
       [-25, -40, -17,  25, -30, -21,  27,   0,  12,  -6],
       [ 34,  31, -21,   1, -12,  26,  33, -37, -37,  26],
       [ 43, -13, -23, -40, -31,  46, -16, -44,  36, -12],
       [ 38, -29, -47,   5, -40, -39, -24,   7, -22,  19]])

In [28]:
temp.max()

47

In [29]:
temp.min()

-47

temp.argmax(

In [33]:
temp.argmax() #return index of max value

7

In [34]:
temp.argmin() #return index of min value

52

In [42]:
reshapeTemp = temp.reshape(4,15)
reshapeTemp

array([[ 12,  35,  38,   8,  14,   2,  37,  47, -15,  23,  -9,  11, -43,
          0, -45],
       [ 10, -20, -15,  13, -37, -25, -40, -17,  25, -30, -21,  27,   0,
         12,  -6],
       [ 34,  31, -21,   1, -12,  26,  33, -37, -37,  26,  43, -13, -23,
        -40, -31],
       [ 46, -16, -44,  36, -12,  38, -29, -47,   5, -40, -39, -24,   7,
        -22,  19]])

In [43]:
temp # np array one dimension

array([ 12,  35,  38,   8,  14,   2,  37,  47, -15,  23,  -9,  11, -43,
         0, -45,  10, -20, -15,  13, -37, -25, -40, -17,  25, -30, -21,
        27,   0,  12,  -6,  34,  31, -21,   1, -12,  26,  33, -37, -37,
        26,  43, -13, -23, -40, -31,  46, -16, -44,  36, -12,  38, -29,
       -47,   5, -40, -39, -24,   7, -22,  19])

In [44]:
reshapeTemp  

array([[ 12,  35,  38,   8,  14,   2,  37,  47, -15,  23,  -9,  11, -43,
          0, -45],
       [ 10, -20, -15,  13, -37, -25, -40, -17,  25, -30, -21,  27,   0,
         12,  -6],
       [ 34,  31, -21,   1, -12,  26,  33, -37, -37,  26,  43, -13, -23,
        -40, -31],
       [ 46, -16, -44,  36, -12,  38, -29, -47,   5, -40, -39, -24,   7,
        -22,  19]])